### PR TITLE
ci: update docker build to include arm64

### PR DESCRIPTION
**Pull request by cwkang1998**
Per title, add workflow to build for `arm64`, taking reference from madara's workflow.

`linux/arm64` might work for Mac M1, but needs further testing.

Closes #1

### CODE REVIEW

**Comment by cwkang1998** [comment]
Test workflow run, with `ubuntu-latest` instead of `ubuntu-latest-32-cores`:
- https://github.com/cwkang1998/madara-app/actions/runs/5314790413/jobs/9622401867

Currently amd64 seems to build successfully but something is making arm64 extremely slow to build, investigating.

**Comment by cwkang1998** [comment]
Successfully built it off CI on my local machine to `amd64` and `arm64`, its slow on arm64 probably due to needing rebuilds on some dependencies for `arm64`.

**Comment by cwkang1998** [comment]
Build took 2 hours, but its working https://github.com/cwkang1998/madara-app/actions/runs/5315748445/jobs/9624492972.

The attached example is failing due to the fact that it has no permission to push to the docker repository.

**Review by AbdelStark — APPROVED** [review]
Lgtm

**Pull request merged**
